# Site wide configuration

title: SmartGuppy Blog
locale: en_US
description: Education, Equality, Empowerment.
logo: site-logo.png
search: true
url: https://blog.smartguppy.com
comments: true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: SmartGuppy
  avatar: bio-photo.png
  email: #you@email.com
  disqus-shortname: smartguppy
  twitter: SmartGuppy
  facebook: smartguppysg
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: smartguppy
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-105976515-2
    verify: sfKtVqgZFs-1RzPOuskTp1D7XBTkNrLhONfbwKxNOCk
    ad-client:
    ad-slot:
  bing-verify: D7A9A6FD9B6DAE4AE1FDC789FA975954
